version: '3.8'

name: EHR_containers

services:
  patient-service:
    image: joebeanzz123/patient_service:latest  # Replace with your desired image
    container_name: patient-service
    ports:
      - "3001:3001"  # Map host port 3001 to container port 3001
    restart: unless-stopped
    environment:
      - DB_URI=mongodb+srv://HartyPotter:alohomora@krustykrab.qgxswyg.mongodb.net/Patient_Service?retryWrites=true&w=majority&appName=KrustyKrab
  
  user-service:
    image: joebeanzz123/user_service
    container_name: user-service
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000
    restart: unless-stopped
    environment:
      - DB_URI=postgresql://neondb_owner:tbYk3h6vzPoy@ep-white-leaf-a5mogkc9-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require
      - JWT_ACCESS_SECRET_KEY="accesssecret"
      - JWT_REFRESH_SECRET_KEY="refreshsecret"
      - JWT_RESET_SECRET_KEY="resetsecret"
      - APP_MAIL="youssefashraf246@gmail.com"
      - APP_MAIL_KEY="wruc lqps zsmd cgwt"
      - REDIS_HOST="redis-14068.c239.us-east-1-2.ec2.redns.redis-cloud.com"
      - REDIS_PORT=14068
      - REDIS_PASS='OS29hReaPP6e75raJEoh7qAsX8MNt5gM'
      - AUTH0_DOMAIN="https://ehr-ai.eu.auth0.com"
      - AUTH0_AUDIENCE="http://localhost:3000"
      - CLIENT_ID='G4nrb4K21vh8YLEoYZqn2O11LMWdyxlc'
      - CLIENT_SECRET='mWKeOq3D48IaT5AZtlpxPj9J6j4CP0oFmFpp8r_c-53OOW5r_mXZY5MINl0DME4E'
